In [45]:
import pandas as pd
import numpy as np

In [46]:
# Setting up a dataframe that takes information from the dump_application.csv file.
application_df = pd.read_csv('dump_application.csv').dropna(axis = 1, how = 'all')

# Take the shape of application_df to find the amount of campers that have applied.
application_df.shape

(943, 23)

In [47]:
# Setting up a dataframe that takes information from the dump_registration.csv file.
registration_df = pd.read_csv('dump_registration.csv').dropna(axis = 1, how = 'all')

# Take the shape of registration_df to find the amount of registered campers.
registration_df.shape

(937, 25)

In [48]:
# Setting up a dataframe that takes information from the dump_camp.csv file.
camp_df = pd.read_csv('dump_camp.csv').dropna(axis = 1, how = 'all')

# Using nested for loops to find the amount of campers that have attended each camp.
for x in camp_df['id']:
    count = 0
    print(x)
    for y in application_df['camp_id']:
        if x == y:
            count += 1
    print(count)
    print()

28
32

24
23

25
38

26
41

12
0

27
41

38
28

1
54

2
21

6
7

3
44

5
20

22
12

16
21

18
19

19
42

20
21

21
23

23
13

17
19

39
0

29
15

37
3

31
31

33
1

30
46

32
30

34
26

35
19

36
3

49
4

48
3

50
7

51
0

47
6

46
29

52
10

44
31

9
0

54
22

40
44

55
24

42
24

43
31

8
0

7
0

53
3

45
12

In [49]:
# Creating a list of the different t-shirt sizes.
t_shirt_list = ['Adult 2XL', 'adult_xxl', 'Adult Extra Large', 'adult_xl', 'Adult Large', 'adult_large', 'Adult Medium', 'adult_meduim', 
                    'Adult Small', 'adult_small', 'Child Large', 'child_large', 'Child Medium', 'child_medium', 'Child Small', 'child_small']

# Using nested for loops to find the amount of campers per t-shirt size.
for x in t_shirt_list: 
    count = 0
    print(x)
    for y in registration_df['t_shirt_size']:
        if y == x:
            count += 1
    print(count)
    print()

Adult 2XL
1

adult_xxl
6

Adult Extra Large
4

adult_xl
18

Adult Large
13

adult_large
106

Adult Medium
35

adult_meduim
154

Adult Small
37

adult_small
161

Child Large
9

child_large
80

Child Medium
2

child_medium
44

Child Small
0

child_small
34

In [50]:
# Making a list of the different season identifiers.
season_list = [1, 2, 3, 4, 5, 6, 7]

# Making a dataframe containing prices above 0.
season_price_df = camp_df[camp_df['price'] > 0]

# Using a nested for loop to total up the price for each camp season.
for x in season_list:
    print(x)
    price_total = 0
    count = 0
    for y in season_price_df['season_id']:
        if y == x:
            price_total += season_price_df['price'].iloc[count]
        count += 1
    print(price_total)
    print()

1
2550

2
5607

3
2875

4
2775

5
6301

6
5383

7
4616

In [51]:
# Setting up a dataframe that takes information from the dump_account.csv file.
account_df = pd.read_csv('dump_account.csv').dropna(axis = 1, how = 'all')

# Creating an empty list that will be used to store the zipcodes of the campers.
zipcode_list = []

# Using a for loop to add each zipcode to the empty list.
for x in account_df['zipcode']:
    zipcode_list.append(x)
    
# Making a new dictionary that will contain the zipcodes and their occurrences.
zipcode_dictionary = dict()

# Using a for loop with an if-else statement to check if the zipcode appears multiple times and increment its occurrences.
for y in zipcode_list:
    if y in zipcode_dictionary:
        zipcode_dictionary[y] += 1
    else:
        zipcode_dictionary[y] = 1

# A filter for the pairs between the zipcode number and its total amount of occurrences to only keep zipcodes with multiple occurrences.      
zipcode_dictionary = {zipcode:campers for zipcode, campers in zipcode_dictionary.items() if campers > 1}

# A for loop that prints each zipcode and the amount of campers to the screen.
for zipcode, campers in zipcode_dictionary.items():
    print(zipcode, ' ', campers)

nan   195
29609   65
46123   4
30058   2
48820   3
77845   2
72756   6
45013   3
1890   2
48059   2
37042   4
30047   3
29687   40
41048   18
38579   2
60504   2
44321   2
37421   3
21701   3
41005   12
32011   2
29651   12
DUPLICATE   2
37122   3
29642   3
41035   5
29680   6
31061   2
43204   2
41092   2
32266   3
45653   2
30004   4
48439   3
28590   2
45314   13
BAD   39
38135   4
97527   2
29650   16
46307   3
38305   2
46143   3
29690   17
28073   2
48108   2
32227   3
30582   2
17545   2
45601   2
44618   2
30534   3
41094   2
32224   9
37064   8
32246   5
29673   3
40229   2
49464   2
29615   29
49508   2
85395   2
37040   3
29349   2
73034   4
37617   4
45069   3
15317   2
53115   2
44090   3
44820   2
41011   2
43015   7
27502   2
30135   4
30039   2
37072   2
42303   2
32225   6
37020   2
32082   9
41076   3
30096   5
BAD ADDRESS   24
40769   2
37043   5
28734   2
44824   2
29614   22
30022   6
30052   2
44221   4
40004   4
29644   4
46350   2
72701   2
45005   2
44436   2
72638   3
49685   2
30265   2
30415   2
30024   3
44077   3
41042   13
32955   2
30040   8
37129   5
37934   2
55932   2
29607   17
30044   4
42104   2
43064   2
42503   3
45102   2
29365   3
45233   3
22407   2
30252   4
37660   2
15212   3
24151   2
37115   2
29936   2
27606   3
72956   4
31904   5
72761   4
44281   3
37075   5
30518   3
63775   2
46237   2
44874   2
43016   3
16335   2
30115   2
64804   3
37086   4
30008   2
43011   2
45065   2
24502   3
37664   2
30120   2
44890   2
35806   3
32257   5
30680   3
44843   2
53137   2
41091   9
32444   2
31601   2
45662   2
32217   2
48616   3
38506   4
30009   2
30116   2
37179   3
37865   2
72715   2
46060   2
44035   3
25414   2
29601   2
36207   3
48188   2
44046   2
31088   2
37013   3
43123   3
28173   2
30350   3
37211   3
72120   4
38016   3
37174   5
32244   3
47150   2
35749   2
35758   4
30813   2
30542   3
37087   5
62704   2
30041   3
32258   3
84770   2
30014   3
37027   3
30076   2
22191   2
30809   3
37067   5
28227   2
30075   2
43402   4
39834   3
45103   2
44094   2
32003   5
45331   2
37049   2
37048   2
32259   5
29617   5
32233   4
45385   2
30528   4
29621   2
32223   4
30736   3
72143   3
72015   3
43040   3
43920   2
42420   2
44691   2
38401   5
43617   2
37085   3
30507   2
43062   2
37073   2
72712   4
30080   2
47342   2
30144   3
47906   2
44846   2
72774   2
30062   2
38654   2
72601   2
37138   2
62451   2
72641   3
37167   2
30215   3
62863   3
44136   2
68046   2
42240   2
64850   2
32250   2
37920   2
41097   3
22554   2
72023   4
32092   2
38464   3
30132   3
37221   2
48186   2
48197   2
32068   4
42330   2
31605   2
45122   2
N8H3V   2
40515   2
74014   2
38018   3
28139   3
92694   2
30519   3
30092   2
37388   3
30127   3
47001   3
28080   2
29073   2
29732   3
26678   2
44216   2
37128   4
15644   2
37725   2
35757   2
44270   3
32034   3
48187   2
30141   2
29662   2
30253   2
31525   7
37363   2
31522   2
27253   2
43748   2
37830   3
92545   2
45150   2
42101   2
40324   2
29681   3
24715   2
41010   3
47304   2
43410   2
32065   3
45660   3
45342   3
46938   2
43026   2
35616   2
30101   3
44224   2
23693   3
46239   3
45053   2
35674   3
28152   2
35405   2
37110   3
38002   2
47203   2
16635   2
10566   3
28761   2
46540   2
72042   2
10562   3
30513   2
29072   3
45309   3
39452   2
36526   3
36582   3
36541   2
70810   2
36575   2
39560   2
39573   2
31545   2
41051   5
27295   3
29456   3
29445   2
25526   2
44070   2
77373   2
45241   2
75034   2
30019   2
75115   2
38017   2
39042   3
8096   2
25801   4
25880   5
25827   2
43065   2
27332   2
47025   3
85308   3
75110   2
30906   2
21108   2
27529   2
41017   3
43229   2
45056   2
44685   2
29301   2
41015   2
72653   2
46158   2
40391   2
60644   2
48840   2
48750   2
41022   2
46151   2
46157   2
31523   4
31520   2
43136   2
10986   2
46033   3
44646   2
34715   2
29805   2
46140   2
72501   3
94061   2